trigger:
  branches:
    include:
      - main

variables:
  # Variables de entorno
  ACR_NAME: 'devopss4'
  IMAGE_NAME: 'myapp-nginx-s4'
  SERVICE_CONNECTION_NAME: 'exp2-s4-docker-connection' 
jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
          dockerfile: '**/Dockerfile'
          tags: |
            latest
        displayName: 'Build and Push Docker Image'